package com.example.androiddevchallenge

import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import com.example.androiddevchallenge.data.Puppy

class MainViewModel : ViewModel() {

  val puppies by mutableStateOf(
    listOf(
      Puppy(id = "30511817", name = "OLIVIA", age = "young", photo = R.drawable.img_olivia, addressCity = "Boston", size = "Large 61-100 lbs (28-45 kg)", sex = "f", breed = "Labrador Retriever", desc = "OLIVIA 1 YEAR Lab/Pointer mix 40lb  Olivia is a very shy girl that will need time to come out of her shell. Loud noises while walking do make her nervous so a confident and experienced owner is important. Since Olivia is nervous with new things, she can be reactive with other dogs if they are too overbearing. Since she will need additional training Olivia will do best in a home as an only dog until she is confident enough to understand she is safe. Olivia is decompressing in her foster home and with time, patience and love Olivia will make the perfect companion. She loves her humans and will follow them around the house wherever they go.  If you are interested in adopting Olivia, Please fill out an adoption application located on our website. PLEASE NOTE: Meet and greets are conducted after an adoption application has been processed and approved. www.aplaceforace.org  *NOTE - If this dog is listed on this site, he/she is still currently available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries daily. Serious applicants, please apply!  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30626113", name = "TSUNAMI", age = "young", photo = R.drawable.img_tsunami, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "m", breed = "American Pit Bull Terrier", desc = "This animal currently has an adoption pending."),
      Puppy(id = "30460740", name = "ARTHUR", age = "adult", photo = R.drawable.img_arthur, addressCity = "Boston", size = "Large 61-100 lbs (28-45 kg)", sex = "m", breed = "German Shepherd Dog", desc = "ARTHUR   Arthur is a 4 year old Shepherd mix. He is very smart ! He knows sit and shake and is even crate trained! Arthur loves dogs but is not cat tested . He is a dog who wants to please his humans and is very sweet!!  www.aplaceforace.org  *NOTE - if this dog is listed on this site, he/she is available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries only, serious applicants can fill out an application on our website*  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30531906", name = "FAITH", age = "young", photo = R.drawable.img_faith, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "f", breed = "Hound (Unknown Type)", desc = "FAITH  2yo female 45# Hound mix  Very friendly - loves everyone and gets along great with dogs. Knows some basic commands but will still need training. Pulls on leash and will need to get used to the crate.  www.aplaceforace.org  NOTE - if this dog is listed on this site, he/she is available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries only, serious applicants can fill out an application on our website*  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30433880", name = "WANDA", age = "adult", photo = R.drawable.img_wanda, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "f", breed = "Chihuahua", desc = "This animal has an adoption pending"),
      Puppy(id = "30641474", name = "RADAR", age = "young", photo = R.drawable.img_ranar, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "m", breed = "Labrador Retriever", desc = "This animal is currently pending adoption"),
      Puppy(id = "30596737", name = "SCOOTER (AND SQUEAKY)", age = "young", photo = R.drawable.img_scooter, addressCity = "Boston", size = "Small 25 lbs (11 kg) or less", sex = "m", breed = "Toy Fox Terrier", desc = "SCOOTER (and SQUEAKY) **BONDED PAIR** male 1 year old 10 pounds toy fox terrier  SCOOTER is Very friendly and out going, he loves being with his brother squeaky. Both were owner surrender to humane society since owner could not keep because apartment complex would not allow. Escape artist and will look for a way out to run and play! Typical chi attitude, will bark at new people. JUMPERS, CAN JUMP HIGH!!  www.aplaceforace.org    *NOTE - If this dog is listed on this site, he/she is still currently available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries daily. Serious applicants, please apply!  also PLEASE NOTE: Meet and greets are conducted after an adoption application has been processed and approved. www.aplaceforace.org  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30596740", name = "SQUEAKY (AND SCOOTER)", age = "young", photo = R.drawable.img_squeaky, addressCity = "Boston", size = "Small 25 lbs (11 kg) or less", sex = "m", breed = "Toy Fox Terrier", desc = "SQUEAKY (and Scooter) **BONDED PAIR** 1 year old male toy fox terrier 10 pounds  Squeaky is very friendly and out going, loves being with his brother Scooter. Both were owner surrender to humane society since owner could not keep because apartment complex would not allow. Good with other dogs. JUMPERS!  www.aplaceforace.org  *NOTE - If this dog is listed on this site, he/she is still currently available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries daily. Serious applicants, please apply!  also PLEASE NOTE: Meet and greets are conducted after an adoption application has been processed and approved. www.aplaceforace.org  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30482252", name = "BAMBI", age = "puppy", photo = R.drawable.img_bambi, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "f", breed = "Labrador Retriever", desc = "BAMBI  Bambi is a 7 month old 25lb lab/terrier mix from Texas. She is nervous at first but does warm up quickly. When she is not running around playing, she enjoys cuddling with her humans. She will need some additional training as she has had little to no structure in her young life. She gets along well with other dogs but is not cat tested.  www.aplaceforace.org  *NOTE - if this dog is listed on this site, he/she is available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries only, serious applicants can fill out an application on our website*  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30618607", name = "JELLY", age = "young", photo = R.drawable.img_jelly, addressCity = "Boston", size = "Large 61-100 lbs (28-45 kg)", sex = "f", breed = "Pointer", desc = "JELLY 2yo. female pointer mix  Jelly is a 2 year old pointer mix that is looking for a very special forever home! She is extremely outgoing and loves to be with her human family at all times! She will play for hours on end and will be sure to keep you laughing. Jelly is a special girl that needs some additional time and attention after being adopted. We are searching for a forever home without children or cats. She has shown fearful reactions to children and it will be best for her to avoid being placed in a home where young children are present. Jelly is housebroken, knows basic commands, food driven and is easily redirected.   Jelly does great with other dogs and is very submissive during play time. We believe Jelly would do well in a home with another dog, however she does have some leash reactivity that needs to be worked on. She will pull and bark at others passing by and is very strong. She has also shown signs of resource guarding her food so it is important to feed separately until this behavior issue has been corrected.  Overall, Jelly is a beautifully sweet dog. She wants to please and is extremely smart. She would do best in a home with a fully fenced in yard and a lot of room to run around! Jelly knows that some of her behaviors might not make her be a first pick but with the proper training, time and patience she will be a completely different girl!  If you are interested in adopting Jelly, please fill out an adoption application located on our website.  PLEASE NOTE: Meet and Greets are only conducted after an application has been submitted and approved  www.aplaceforace.org  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30537881", name = "CARMEN", age = "young", photo = R.drawable.img_carmen, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "f", breed = "Shepherd (Unknown Type)", desc = "Carmen is a 3 year old shepherd mix that weighs about 25lbs. She is very shy, timid and nervous with new things and will need a patient adopter who will give her the time and training required to become the best companion. She gets along well with other dogs and may do best in a home with another confident dog to show her the ropes. She was rescued from a shelter where she was so terrified. She currently getting more and more comfortable each day with her foster and learning new things.  If you are interested in adopting Carmen, Please fill out an adoption application located on our website. PLEASE NOTE: Meet and greets are conducted after an adoption application has been processed and approved. www.aplaceforace.org  *NOTE - If this dog is listed on this site, he/she is still currently available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries daily. Serious applicants, please apply!  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
      Puppy(id = "30482301", name = "SMITH", age = "puppy", photo = R.drawable.img_smith, addressCity = "Boston", size = "Med. 26-60 lbs (12-27 kg)", sex = "m", breed = "Labrador Retriever", desc = "Smith is an 8 month old, 50lb lab/border collie mix from Texas! He was rescued form a shelter and is currently learning how to live life in a home! Smith has had very little structure in his young life and wants nothing but love from his humans! He will need some training with basic commands and he has shown signs of resource guarding his food when other dogs are near. An experienced adopter is needed for Smith as he will need additional time and patience spent with him to work through any challenges he may experience as he continues to grow! Smith loves everyone and will play non-stop, an active household will be best for Smith! Smith does love other dogs and will play all day long. Adopters would need to remain vigilant with toys, treats and food bowls with other dogs until Smith understands that their is enough for everyone! Smith is looking for that perfect home where he can run, play, give unlimited amount of kisses and relax on the couch, could that be with you?!  If you are interested in adopting , Please fill out an adoption application located on our website. PLEASE NOTE: Meet and greets are conducted after an adoption application has been processed and approved. www.aplaceforace.org  *NOTE - If this dog is listed on this site, he/she is still currently available; consideration is given to those who submit actual applications first. We receive an enormous amount of inquiries daily. Serious applicants, please apply!  attn: due to the overwhelming response of applications, APFA is requesting a \$20 non-refundable application fee prior to completing our adoption application/process. However, once approved to adopt, your \$20 will be applied to the adoption fee."),
    )
  )

  private var adoptionList: Set<String>  by mutableStateOf(
    emptySet()
  )

  var currentPuppy: Puppy? by mutableStateOf(null)
    private set

  fun showPuppyDetail(puppy: Puppy) {
    currentPuppy = puppy
  }

  fun hidePuppy() {
    currentPuppy = null
  }

  fun toggleAdoption(puppy: Puppy) {
    adoptionList = if (puppy.id in adoptionList) {
      adoptionList - puppy.id
    } else {
      adoptionList + puppy.id
    }
  }

  fun isAdoption(puppy: Puppy) = puppy.id in adoptionList

}